module.exports = {
  ResourceList: require('./lib/ResourceList.jsx'),
  ResourceTable: require('./lib/ResourceTable.jsx'),
  ResourceSelect: require('./lib/ResourceSelect.jsx'),
  singleResource: require('./lib/mixins/singleResource.jsx'),
  login: require("./lib/mixins/login.jsx"),
  form: require("./lib/mixins/form.js"),
  paginate: require("./lib/mixins/paginate.js"),
  PagedResourceList: paginate(ResourceList),
  Router: require("./lib/Router.js"),
  keepPageNumberInUrl: require("./lib/mixins/keep-page-number-in-url.js"),
  keepPageNumberInState: require("./lib/mixins/keep-page-number-in-state.js"),
  RouterLink: require("./lib/RouterLink.js"),
  propsFromUrl: require("./lib/mixins/props-from-url.js"),
  CachedHttp: require("./lib/cached-http.js"),
  loadCollectionSpecification: require("./lib/mixins/load-collection-specification.js"),
  StatefulCollection: require("./lib/stateful-collection.js"),
  PaginationUI: require("./lib/pagination-ui.jsx"),
  PropMultiplexer: require("./lib/prop-multiplexer.js")
};
